---
version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /path/t o/your/config:/etc/nginx/conf.d
  mariadb:
    image: "mariadb:latest"
    restart: 'always'
    volumes: 
      - "/var/lib/mysql/data:/var/lib/mysql"     
      - "/var/lib/mysql/logs:/var/log/mysql"     
      - "/var/docker/mariadb/conf:/etc/mysql"    
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "test"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "test"
    ports:
      - "3306:3306"
